export const MCHAT_CONSTANTS = [
    {
      id: 1,
      question: "If you point at something across the room, does your child look at it?",
      example: "FOR EXAMPLE, if you point at a toy or an animal, does your child look at the toy or animal?",
      passLabel: "Pass",
      failLabel: "Fail",
    },
    {
      id: 2,
      question: "Have you ever wondered if your child might be deaf?",
      passLabel: "Pass",
      failLabel: "Fail",
    },
    {
      id: 3,
      question: "Does your child play pretend or make-believe?",
      example: "FOR EXAMPLE, pretend to drink from an empty cup, pretend to talk on a phone, or pretend to feed a doll or stuffed animal",
      passLabel: "Pass",
      failLabel: "Fail",
    },
    {
      id: 4,
      question: "Does your child like climbing on things?",
      example: "FOR EXAMPLE, furniture, playground equipment, or stairs",
      passLabel: "Pass",
      failLabel: "Fail",
    },
    {
      id: 5,
      question: "Does your child make unusual finger movements near his or her eyes?",
      example: "FOR EXAMPLE, does your child wiggle his or her fingers close to his or her eyes?",
      passLabel: "Pass",
      failLabel: "Fail",
    },
    {
      id: 6,
      question: "Does your child point with one finger to ask for something or to get help?",
      example: "FOR EXAMPLE, pointing to a snack or toy that is out of reach",
      passLabel: "Pass",
      failLabel: "Fail",
    },
    {
      id: 7,
      question: "Does your child point with one finger to show you something interesting?",
      example: "FOR EXAMPLE, pointing to an airplane in the sky or a big truck in the road",
      passLabel: "Pass",
      failLabel: "Fail",
    },
    {
      id: 8,
      question: "Is your child interested in other children?",
      example: "FOR EXAMPLE, does your child watch other children, smile at them, or go to them?",
      passLabel: "Pass",
      failLabel: "Fail",
    },
    {
      id: 9,
      question: "Does your child show you things by bringing them to you or holding them up for you to see—not to get help, but just to share?",
      example: "FOR EXAMPLE, showing you a flower, a stuffed animal, or a toy truck",
      passLabel: "Pass",
      failLabel: "Fail",
    },
    {
      id: 10,
      question: "Does your child respond when you call his or her name?",
      example: "FOR EXAMPLE, does he or she look up, talk or babble, or stop what he or she is doing when you call his or her name?",
      passLabel: "Pass",
      failLabel: "Fail",
    },
    {
      id: 11,
      question: "When you smile at your child, does he or she smile back at you?",
      passLabel: "Pass",
      failLabel: "Fail",
    },
    {
      id: 12,
      question: "Does your child get upset by everyday noises?",
      example: "FOR EXAMPLE, vacuum cleaner or loud music",
      passLabel: "Pass",
      failLabel: "Fail",
    },
    {
      id: 13,
      question: "Does your child walk?",
      passLabel: "Pass",
      failLabel: "Fail",
    },
    {
      id: 14,
      question: "Does your child look you in the eye when you are talking to him or her, playing with him or her, or dressing him or her?",
      passLabel: "Pass",
      failLabel: "Fail",
    },
    {
      id: 15,
      question: "Does your child try to copy what you do?",
      example: "FOR EXAMPLE, wave bye-bye, clap, or make a funny noise when you do",
      passLabel: "Pass",
      failLabel: "Fail",
    },
    {
      id: 16,
      question: "If you turn your head to look at something, does your child look around to see what you are looking at?",
      passLabel: "Pass",
      failLabel: "Fail",
    },
    {
      id: 17,
      question: "Does your child try to get you to watch him or her?",
      example: "FOR EXAMPLE, does your child look at you for praise, or say “look” or “watch me”",
      passLabel: "Pass",
      failLabel: "Fail",
    },
    {
      id: 18,
      question: "Does your child understand when you tell him or her to do something?",
      example: "FOR EXAMPLE, if you don’t point, can your child understand “put the book on the chair” or “bring me the blanket”?",
      passLabel: "Pass",
      failLabel: "Fail",
    },
    {
      id: 19,
      question: "If something new happens, does your child look at your face to see how you feel about it?",
      example: "FOR EXAMPLE, if he or she hears a strange or funny noise, or sees a new toy, will he or she look at your face?",
      passLabel: "Pass",
      failLabel: "Fail",
    },
    {
      id: 20,
      question: "Does your child like movement activities?",
      example: "FOR EXAMPLE, being swung or bounced on your knee",
      passLabel: "Pass",
      failLabel: "Fail",
    },
  ];
  